# Generated by Django 3.1.4 on 2020-12-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(max_length=60)),
                ('cut', models.TextField(max_length=60)),
                ('clarity', models.TextField(max_length=60)),
                ('caratWeight', models.TextField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='alias',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.TextField(max_length=60),
        ),
    ]
